Add Clipboard Interactions and User Input Suggestions
akarshanbiswas/rich-chat pull request #5
Opened 2024-02-22 03:52 UTC by teleprint-me

In this PR, I've been drafting Clipboard Interactions and User Input Suggestions to the project using Pyperclip for clipboard management and regular expressions for extracting code snippets from messages.

Key Features:

* Added custom key bindings for copying messages or code snippets to the clipboard using Pyperclip.
* Implemented regular expressions to extract and copy only code snippets from messages using Pyperclip.
* Added AutoSuggestFromHistory to provide input suggestions based on past entries when using the user input suggestions feature.

Technical Details:

* Added Pyperclip dependency for clipboard management using pip install Pyperclip.
* Implemented PyperclipClipboard class for Pyperclip integration.
* Implemented regular expression pattern matching using re module and re.compile() method for extracting code snippets from messages using Pyperclip.
* Implemented AutoSuggestFromHistory functionality using history module for providing input suggestions based on past entries.

Goal:

This PR is an opportunity to experiment and draft how we could implement Clipboard Interactions and User Input Suggestions to the project using Pyperclip for clipboard management and regular expressions for extracting code snippets from messages. 

This also provides us with the opportunity to plan out and design custom key bindings for copying messages or code snippets to the clipboard. 

These features should make using the project more convenient and efficient for users.

2024-02-22 04:15 UTC, akarshanbiswas requested changes
I think it is better to move ChatHistory class to its own file `ChatHistory.py` to keep track of future changes. We can import it as a library in the main rich-chat.py.

2024-02-25 16:21 UTC, teleprint-me commented
I'll do this either later tonight or tomorrow. I'm in the middle of a few personal projects and I just started working again, still trying to get back into the swing of things. Moving the source code to a new module is trivial. 

Maybe think about making `source` a proper package by adding an `__init__.py` and renaming it to `rich_chat`? I think we should do this in a separate PR once we merge this PR and iron out the basics.

What do you think?

2024-02-25 17:09 UTC, akarshanbiswas commented
Interesting. I already did this on my PC. Yes sure because we will have different modules.

2024-02-25 21:42 UTC, teleprint-me commented
> Interesting. I already did this on my PC.

Okay. I bit the bullet.

It's the same as before, with the difference that it's a executable module, e.g.

```sh
python -m rich_chat.rich-chat --help
```

I've also given some thought to the naming convention for the "rich_chat" module, and I think following the Python convention of using an underscore (_) for library modules would be a good idea for consistency. This means renaming the current "rich-chat.py" file to something like "rich_chat.py" or "rich_chat_cli.py".

Here's how we could run the module as an executable using this new naming convention:

```sh
python -m rich_chat.rich_chat_cli --help
```

The decision on which naming convention to use depends.

Alternatively, we could use `__main__.py` for the entry point file, but that would require encapsulating all packages and modules within the package structure. This approach has its own set of pros and cons, such as increased complexity and better encapsulation.

2024-03-02 19:26 UTC, teleprint-me commented
I think this is a good checkpoint for the current implementation.

The introduced keybindings are designed to minimize conflicts with commonly used shortcuts, offering a straightforward way for users to interact with past messages, especially for yanking text:

- **`ctrl + s`**: Initiates control selection.
- **`ctrl + s a`**: Selects all text from a message.
- **`ctrl + s s`**: Specifically selects code snippets within a message.

For instance, **`ctrl + s s 1`** would copy a code snippet from the most recent message into the clipboard, assuming a snippet exists. To extract from specific messages, users can easily adjust the trailing digit, such as **`ctrl + s s 3`** for a snippet from the third most recent message. Similarly, **`ctrl + s a 1`** would copy the entirety of the most recent message.

This setup is admittedly basic and could benefit from refinement. It's a starting point, enabling some level of functionality while we explore other approaches.

I'm open to feedback, particularly any ideas to enhance usability or introduce more intuitive interactions.

2025-07-16 23:09 UTC, closed without merging